'use strict';
(() => {
const CFG={url:'https://bezyisxfaosbygkknkun.supabase.co',key:'sb_publishable_TBzvf_obpTx9O0-T9wdPNg_EHt44lMK'};
const state={client:null,user:null,householdId:null,statuses:new Map(),ratings:new Map(),ready:false};
const statusKey=(d,id)=>`${d}|${id}`;
function localStatus(d,id){return localStorage.getItem(`ffm-meal-status-${d}-${id}`)||'planned'}
function localRating(id){return Number(localStorage.getItem(`ffm-rating-${id}`)||0)}
function injectAuth(){const nav=document.querySelector('.nav'); if(!nav||document.querySelector('#ffmAccount'))return; const box=document.createElement('div'); box.id='ffmAccount'; box.className='account'; box.innerHTML='<button id="ffmAccountBtn" class="accountBtn" type="button">Sign in</button>'; nav.appendChild(box); box.querySelector('button').onclick=()=>state.user?signOut():openLogin();}
function renderAuth(){const b=document.querySelector('#ffmAccountBtn'); if(b)b.textContent=state.user?'Sign out':'Sign in'; document.body.classList.toggle('ffmSignedIn',!!state.user)}
function openLogin(){let m=document.querySelector('#ffmLogin');if(!m){m=document.createElement('div');m.id='ffmLogin';m.className='modal';m.innerHTML='<div class="modalbox"><div class="day">Flores Family</div><h2>Sign in</h2><p class="sub">Sign in to sync ratings and meal status across your family devices.</p><label class="authField">Email<input id="ffmEmail" type="email" autocomplete="email"></label><label class="authField">Password<input id="ffmPassword" type="password" autocomplete="current-password"></label><div id="ffmAuthError" class="authError"></div><div class="btns"><button class="btn" id="ffmSignIn">Sign in</button><button class="btn alt" id="ffmCancel">Cancel</button></div></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)closeLogin()};m.querySelector('#ffmCancel').onclick=closeLogin;m.querySelector('#ffmSignIn').onclick=async()=>{const err=m.querySelector('#ffmAuthError');err.textContent='';const email=m.querySelector('#ffmEmail').value.trim(),password=m.querySelector('#ffmPassword').value;const {error}=await state.client.auth.signInWithPassword({email,password});if(error)err.textContent=error.message;else closeLogin()};}m.classList.add('open');setTimeout(()=>m.querySelector('#ffmEmail').focus(),20)}
function closeLogin(){document.querySelector('#ffmLogin')?.classList.remove('open')}
async function signOut(){await state.client.auth.signOut()}
async function loadCloud(){state.statuses.clear();state.ratings.clear();state.householdId=null;if(!state.user){state.ready=true;notify();return}const {data:h,error:he}=await state.client.from('households').select('id').limit(1).maybeSingle();if(he||!h){console.error('Household lookup failed',he);state.ready=true;notify();return}state.householdId=h.id;const [{data:s,error:se},{data:r,error:re}]=await Promise.all([state.client.from('meal_status').select('meal_date,entry_id,status'),state.client.from('recipe_ratings').select('recipe_id,rating')]);if(se)console.error(se);if(re)console.error(re);(s||[]).forEach(x=>state.statuses.set(statusKey(x.meal_date,x.entry_id),x.status));(r||[]).forEach(x=>state.ratings.set(x.recipe_id,Number(x.rating)));await migrateLocal();state.ready=true;notify()}
async function migrateLocal(){if(!state.user||!state.householdId||localStorage.getItem('ffm-cloud-migrated-v1'))return;const jobs=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith('ffm-rating-')){const id=k.slice(11),rating=Number(localStorage.getItem(k));if(rating&&!state.ratings.has(id))jobs.push(setRating(id,rating,false));}else if(k?.startsWith('ffm-meal-status-')){const rest=k.slice(16),m=rest.match(/^(\d{4}-\d{2}-\d{2})-(.+)$/);if(m&&!state.statuses.has(statusKey(m[1],m[2])))jobs.push(setStatus(m[1],m[2],localStorage.getItem(k),m[2].startsWith('date-night-')?'dinner_date':'recipe',false));}}await Promise.allSettled(jobs);localStorage.setItem('ffm-cloud-migrated-v1','1')}
function notify(){renderAuth();window.dispatchEvent(new CustomEvent('ffm-cloud-change',{detail:{signedIn:!!state.user}}))}
async function setStatus(date,id,status,type='recipe',emit=true){if(!state.user||!state.householdId){if(status==='planned')localStorage.removeItem(`ffm-meal-status-${date}-${id}`);else localStorage.setItem(`ffm-meal-status-${date}-${id}`,status);if(emit)notify();return true}const k=statusKey(date,id);if(status==='planned'){const {error}=await state.client.from('meal_status').delete().eq('household_id',state.householdId).eq('meal_date',date);if(error){console.error(error);return false}state.statuses.delete(k)}else{const row={household_id:state.householdId,meal_date:date,entry_id:id,entry_type:type,status,updated_by:state.user.id,updated_at:new Date().toISOString()};const {error}=await state.client.from('meal_status').upsert(row,{onConflict:'household_id,meal_date'});if(error){console.error(error);return false}state.statuses.set(k,status)}if(emit)notify();return true}
async function setRating(id,rating,emit=true){if(!state.user||!state.householdId){localStorage.setItem(`ffm-rating-${id}`,String(rating));if(emit)notify();return true}const row={household_id:state.householdId,recipe_id:id,rating,updated_by:state.user.id,updated_at:new Date().toISOString()};const {error}=await state.client.from('recipe_ratings').upsert(row,{onConflict:'household_id,recipe_id'});if(error){console.error(error);return false}state.ratings.set(id,Number(rating));if(emit)notify();return true}
window.FFMCloud={state,getStatus:(d,id)=>state.user?(state.statuses.get(statusKey(d,id))||'planned'):localStatus(d,id),setStatus,getRating:id=>state.user?(state.ratings.get(id)||0):localRating(id),setRating,openLogin};
async function init(){injectAuth();if(!window.supabase){console.error('Supabase library unavailable');state.ready=true;notify();return}state.client=window.supabase.createClient(CFG.url,CFG.key,{auth:{persistSession:true,autoRefreshToken:true}});const {data}=await state.client.auth.getSession();state.user=data.session?.user||null;await loadCloud();state.client.auth.onAuthStateChange(async(_e,session)=>{state.user=session?.user||null;await loadCloud()});}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
